version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: sim-poliklinik-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=simrs
        - MYSQL_DATABASE=sim_rs
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: sim-poliklinik-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: sim-poliklinik-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
